// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package rewardchain

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Partner                       protoreflect.MessageDescriptor
	fd_Partner_id                    protoreflect.FieldDescriptor
	fd_Partner_name                  protoreflect.FieldDescriptor
	fd_Partner_category              protoreflect.FieldDescriptor
	fd_Partner_location              protoreflect.FieldDescriptor
	fd_Partner_country               protoreflect.FieldDescriptor
	fd_Partner_disabled              protoreflect.FieldDescriptor
	fd_Partner_total_liquidity       protoreflect.FieldDescriptor
	fd_Partner_available_liquidity   protoreflect.FieldDescriptor
	fd_Partner_on_hold_liquidity     protoreflect.FieldDescriptor
	fd_Partner_earn_cost_per_point   protoreflect.FieldDescriptor
	fd_Partner_redeem_cost_per_point protoreflect.FieldDescriptor
	fd_Partner_starts_from           protoreflect.FieldDescriptor
	fd_Partner_ends_before           protoreflect.FieldDescriptor
)

func init() {
	file_rewardchain_rewardchain_partner_proto_init()
	md_Partner = File_rewardchain_rewardchain_partner_proto.Messages().ByName("Partner")
	fd_Partner_id = md_Partner.Fields().ByName("id")
	fd_Partner_name = md_Partner.Fields().ByName("name")
	fd_Partner_category = md_Partner.Fields().ByName("category")
	fd_Partner_location = md_Partner.Fields().ByName("location")
	fd_Partner_country = md_Partner.Fields().ByName("country")
	fd_Partner_disabled = md_Partner.Fields().ByName("disabled")
	fd_Partner_total_liquidity = md_Partner.Fields().ByName("total_liquidity")
	fd_Partner_available_liquidity = md_Partner.Fields().ByName("available_liquidity")
	fd_Partner_on_hold_liquidity = md_Partner.Fields().ByName("on_hold_liquidity")
	fd_Partner_earn_cost_per_point = md_Partner.Fields().ByName("earn_cost_per_point")
	fd_Partner_redeem_cost_per_point = md_Partner.Fields().ByName("redeem_cost_per_point")
	fd_Partner_starts_from = md_Partner.Fields().ByName("starts_from")
	fd_Partner_ends_before = md_Partner.Fields().ByName("ends_before")
}

var _ protoreflect.Message = (*fastReflection_Partner)(nil)

type fastReflection_Partner Partner

func (x *Partner) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Partner)(x)
}

func (x *Partner) slowProtoReflect() protoreflect.Message {
	mi := &file_rewardchain_rewardchain_partner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Partner_messageType fastReflection_Partner_messageType
var _ protoreflect.MessageType = fastReflection_Partner_messageType{}

type fastReflection_Partner_messageType struct{}

func (x fastReflection_Partner_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Partner)(nil)
}
func (x fastReflection_Partner_messageType) New() protoreflect.Message {
	return new(fastReflection_Partner)
}
func (x fastReflection_Partner_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Partner
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Partner) Descriptor() protoreflect.MessageDescriptor {
	return md_Partner
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Partner) Type() protoreflect.MessageType {
	return _fastReflection_Partner_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Partner) New() protoreflect.Message {
	return new(fastReflection_Partner)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Partner) Interface() protoreflect.ProtoMessage {
	return (*Partner)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Partner) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Partner_id, value) {
			return
		}
	}
	if x.Name != "" {
		value := protoreflect.ValueOfString(x.Name)
		if !f(fd_Partner_name, value) {
			return
		}
	}
	if x.Category != "" {
		value := protoreflect.ValueOfString(x.Category)
		if !f(fd_Partner_category, value) {
			return
		}
	}
	if x.Location != "" {
		value := protoreflect.ValueOfString(x.Location)
		if !f(fd_Partner_location, value) {
			return
		}
	}
	if x.Country != "" {
		value := protoreflect.ValueOfString(x.Country)
		if !f(fd_Partner_country, value) {
			return
		}
	}
	if x.Disabled != false {
		value := protoreflect.ValueOfBool(x.Disabled)
		if !f(fd_Partner_disabled, value) {
			return
		}
	}
	if x.TotalLiquidity != "" {
		value := protoreflect.ValueOfString(x.TotalLiquidity)
		if !f(fd_Partner_total_liquidity, value) {
			return
		}
	}
	if x.AvailableLiquidity != "" {
		value := protoreflect.ValueOfString(x.AvailableLiquidity)
		if !f(fd_Partner_available_liquidity, value) {
			return
		}
	}
	if x.OnHoldLiquidity != "" {
		value := protoreflect.ValueOfString(x.OnHoldLiquidity)
		if !f(fd_Partner_on_hold_liquidity, value) {
			return
		}
	}
	if x.EarnCostPerPoint != "" {
		value := protoreflect.ValueOfString(x.EarnCostPerPoint)
		if !f(fd_Partner_earn_cost_per_point, value) {
			return
		}
	}
	if x.RedeemCostPerPoint != "" {
		value := protoreflect.ValueOfString(x.RedeemCostPerPoint)
		if !f(fd_Partner_redeem_cost_per_point, value) {
			return
		}
	}
	if x.StartsFrom != "" {
		value := protoreflect.ValueOfString(x.StartsFrom)
		if !f(fd_Partner_starts_from, value) {
			return
		}
	}
	if x.EndsBefore != "" {
		value := protoreflect.ValueOfString(x.EndsBefore)
		if !f(fd_Partner_ends_before, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Partner) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "rewardchain.rewardchain.Partner.id":
		return x.Id != uint64(0)
	case "rewardchain.rewardchain.Partner.name":
		return x.Name != ""
	case "rewardchain.rewardchain.Partner.category":
		return x.Category != ""
	case "rewardchain.rewardchain.Partner.location":
		return x.Location != ""
	case "rewardchain.rewardchain.Partner.country":
		return x.Country != ""
	case "rewardchain.rewardchain.Partner.disabled":
		return x.Disabled != false
	case "rewardchain.rewardchain.Partner.total_liquidity":
		return x.TotalLiquidity != ""
	case "rewardchain.rewardchain.Partner.available_liquidity":
		return x.AvailableLiquidity != ""
	case "rewardchain.rewardchain.Partner.on_hold_liquidity":
		return x.OnHoldLiquidity != ""
	case "rewardchain.rewardchain.Partner.earn_cost_per_point":
		return x.EarnCostPerPoint != ""
	case "rewardchain.rewardchain.Partner.redeem_cost_per_point":
		return x.RedeemCostPerPoint != ""
	case "rewardchain.rewardchain.Partner.starts_from":
		return x.StartsFrom != ""
	case "rewardchain.rewardchain.Partner.ends_before":
		return x.EndsBefore != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rewardchain.rewardchain.Partner"))
		}
		panic(fmt.Errorf("message rewardchain.rewardchain.Partner does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Partner) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "rewardchain.rewardchain.Partner.id":
		x.Id = uint64(0)
	case "rewardchain.rewardchain.Partner.name":
		x.Name = ""
	case "rewardchain.rewardchain.Partner.category":
		x.Category = ""
	case "rewardchain.rewardchain.Partner.location":
		x.Location = ""
	case "rewardchain.rewardchain.Partner.country":
		x.Country = ""
	case "rewardchain.rewardchain.Partner.disabled":
		x.Disabled = false
	case "rewardchain.rewardchain.Partner.total_liquidity":
		x.TotalLiquidity = ""
	case "rewardchain.rewardchain.Partner.available_liquidity":
		x.AvailableLiquidity = ""
	case "rewardchain.rewardchain.Partner.on_hold_liquidity":
		x.OnHoldLiquidity = ""
	case "rewardchain.rewardchain.Partner.earn_cost_per_point":
		x.EarnCostPerPoint = ""
	case "rewardchain.rewardchain.Partner.redeem_cost_per_point":
		x.RedeemCostPerPoint = ""
	case "rewardchain.rewardchain.Partner.starts_from":
		x.StartsFrom = ""
	case "rewardchain.rewardchain.Partner.ends_before":
		x.EndsBefore = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rewardchain.rewardchain.Partner"))
		}
		panic(fmt.Errorf("message rewardchain.rewardchain.Partner does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Partner) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "rewardchain.rewardchain.Partner.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "rewardchain.rewardchain.Partner.name":
		value := x.Name
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.category":
		value := x.Category
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.location":
		value := x.Location
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.country":
		value := x.Country
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.disabled":
		value := x.Disabled
		return protoreflect.ValueOfBool(value)
	case "rewardchain.rewardchain.Partner.total_liquidity":
		value := x.TotalLiquidity
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.available_liquidity":
		value := x.AvailableLiquidity
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.on_hold_liquidity":
		value := x.OnHoldLiquidity
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.earn_cost_per_point":
		value := x.EarnCostPerPoint
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.redeem_cost_per_point":
		value := x.RedeemCostPerPoint
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.starts_from":
		value := x.StartsFrom
		return protoreflect.ValueOfString(value)
	case "rewardchain.rewardchain.Partner.ends_before":
		value := x.EndsBefore
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rewardchain.rewardchain.Partner"))
		}
		panic(fmt.Errorf("message rewardchain.rewardchain.Partner does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Partner) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "rewardchain.rewardchain.Partner.id":
		x.Id = value.Uint()
	case "rewardchain.rewardchain.Partner.name":
		x.Name = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.category":
		x.Category = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.location":
		x.Location = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.country":
		x.Country = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.disabled":
		x.Disabled = value.Bool()
	case "rewardchain.rewardchain.Partner.total_liquidity":
		x.TotalLiquidity = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.available_liquidity":
		x.AvailableLiquidity = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.on_hold_liquidity":
		x.OnHoldLiquidity = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.earn_cost_per_point":
		x.EarnCostPerPoint = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.redeem_cost_per_point":
		x.RedeemCostPerPoint = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.starts_from":
		x.StartsFrom = value.Interface().(string)
	case "rewardchain.rewardchain.Partner.ends_before":
		x.EndsBefore = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rewardchain.rewardchain.Partner"))
		}
		panic(fmt.Errorf("message rewardchain.rewardchain.Partner does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Partner) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "rewardchain.rewardchain.Partner.id":
		panic(fmt.Errorf("field id of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.name":
		panic(fmt.Errorf("field name of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.category":
		panic(fmt.Errorf("field category of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.location":
		panic(fmt.Errorf("field location of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.country":
		panic(fmt.Errorf("field country of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.disabled":
		panic(fmt.Errorf("field disabled of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.total_liquidity":
		panic(fmt.Errorf("field total_liquidity of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.available_liquidity":
		panic(fmt.Errorf("field available_liquidity of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.on_hold_liquidity":
		panic(fmt.Errorf("field on_hold_liquidity of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.earn_cost_per_point":
		panic(fmt.Errorf("field earn_cost_per_point of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.redeem_cost_per_point":
		panic(fmt.Errorf("field redeem_cost_per_point of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.starts_from":
		panic(fmt.Errorf("field starts_from of message rewardchain.rewardchain.Partner is not mutable"))
	case "rewardchain.rewardchain.Partner.ends_before":
		panic(fmt.Errorf("field ends_before of message rewardchain.rewardchain.Partner is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rewardchain.rewardchain.Partner"))
		}
		panic(fmt.Errorf("message rewardchain.rewardchain.Partner does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Partner) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "rewardchain.rewardchain.Partner.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "rewardchain.rewardchain.Partner.name":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.category":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.location":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.country":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.disabled":
		return protoreflect.ValueOfBool(false)
	case "rewardchain.rewardchain.Partner.total_liquidity":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.available_liquidity":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.on_hold_liquidity":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.earn_cost_per_point":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.redeem_cost_per_point":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.starts_from":
		return protoreflect.ValueOfString("")
	case "rewardchain.rewardchain.Partner.ends_before":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: rewardchain.rewardchain.Partner"))
		}
		panic(fmt.Errorf("message rewardchain.rewardchain.Partner does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Partner) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in rewardchain.rewardchain.Partner", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Partner) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Partner) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Partner) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Partner) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Partner)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		l = len(x.Name)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Category)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Location)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Country)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Disabled {
			n += 2
		}
		l = len(x.TotalLiquidity)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AvailableLiquidity)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OnHoldLiquidity)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.EarnCostPerPoint)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.RedeemCostPerPoint)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.StartsFrom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.EndsBefore)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Partner)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.EndsBefore) > 0 {
			i -= len(x.EndsBefore)
			copy(dAtA[i:], x.EndsBefore)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.EndsBefore)))
			i--
			dAtA[i] = 0x6a
		}
		if len(x.StartsFrom) > 0 {
			i -= len(x.StartsFrom)
			copy(dAtA[i:], x.StartsFrom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.StartsFrom)))
			i--
			dAtA[i] = 0x62
		}
		if len(x.RedeemCostPerPoint) > 0 {
			i -= len(x.RedeemCostPerPoint)
			copy(dAtA[i:], x.RedeemCostPerPoint)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.RedeemCostPerPoint)))
			i--
			dAtA[i] = 0x5a
		}
		if len(x.EarnCostPerPoint) > 0 {
			i -= len(x.EarnCostPerPoint)
			copy(dAtA[i:], x.EarnCostPerPoint)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.EarnCostPerPoint)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.OnHoldLiquidity) > 0 {
			i -= len(x.OnHoldLiquidity)
			copy(dAtA[i:], x.OnHoldLiquidity)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OnHoldLiquidity)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.AvailableLiquidity) > 0 {
			i -= len(x.AvailableLiquidity)
			copy(dAtA[i:], x.AvailableLiquidity)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AvailableLiquidity)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.TotalLiquidity) > 0 {
			i -= len(x.TotalLiquidity)
			copy(dAtA[i:], x.TotalLiquidity)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TotalLiquidity)))
			i--
			dAtA[i] = 0x3a
		}
		if x.Disabled {
			i--
			if x.Disabled {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x30
		}
		if len(x.Country) > 0 {
			i -= len(x.Country)
			copy(dAtA[i:], x.Country)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Country)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Location) > 0 {
			i -= len(x.Location)
			copy(dAtA[i:], x.Location)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Location)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Category) > 0 {
			i -= len(x.Category)
			copy(dAtA[i:], x.Category)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Category)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Name) > 0 {
			i -= len(x.Name)
			copy(dAtA[i:], x.Name)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Name)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Partner)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Partner: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Partner: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Name = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Category = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Location = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Country", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Country = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Disabled", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Disabled = bool(v != 0)
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalLiquidity", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TotalLiquidity = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AvailableLiquidity", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AvailableLiquidity = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OnHoldLiquidity", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OnHoldLiquidity = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EarnCostPerPoint", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.EarnCostPerPoint = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RedeemCostPerPoint", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.RedeemCostPerPoint = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 12:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StartsFrom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.StartsFrom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 13:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EndsBefore", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.EndsBefore = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: rewardchain/rewardchain/partner.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Partner defines an on-chain partner record.
type Partner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category           string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Location           string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Country            string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Disabled           bool   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	TotalLiquidity     string `protobuf:"bytes,7,opt,name=total_liquidity,json=totalLiquidity,proto3" json:"total_liquidity,omitempty"`
	AvailableLiquidity string `protobuf:"bytes,8,opt,name=available_liquidity,json=availableLiquidity,proto3" json:"available_liquidity,omitempty"`
	OnHoldLiquidity    string `protobuf:"bytes,9,opt,name=on_hold_liquidity,json=onHoldLiquidity,proto3" json:"on_hold_liquidity,omitempty"`
	EarnCostPerPoint   string `protobuf:"bytes,10,opt,name=earn_cost_per_point,json=earnCostPerPoint,proto3" json:"earn_cost_per_point,omitempty"`
	RedeemCostPerPoint string `protobuf:"bytes,11,opt,name=redeem_cost_per_point,json=redeemCostPerPoint,proto3" json:"redeem_cost_per_point,omitempty"`
	StartsFrom         string `protobuf:"bytes,12,opt,name=starts_from,json=startsFrom,proto3" json:"starts_from,omitempty"`
	EndsBefore         string `protobuf:"bytes,13,opt,name=ends_before,json=endsBefore,proto3" json:"ends_before,omitempty"`
}

func (x *Partner) Reset() {
	*x = Partner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rewardchain_rewardchain_partner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partner) ProtoMessage() {}

// Deprecated: Use Partner.ProtoReflect.Descriptor instead.
func (*Partner) Descriptor() ([]byte, []int) {
	return file_rewardchain_rewardchain_partner_proto_rawDescGZIP(), []int{0}
}

func (x *Partner) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Partner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Partner) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Partner) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Partner) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Partner) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Partner) GetTotalLiquidity() string {
	if x != nil {
		return x.TotalLiquidity
	}
	return ""
}

func (x *Partner) GetAvailableLiquidity() string {
	if x != nil {
		return x.AvailableLiquidity
	}
	return ""
}

func (x *Partner) GetOnHoldLiquidity() string {
	if x != nil {
		return x.OnHoldLiquidity
	}
	return ""
}

func (x *Partner) GetEarnCostPerPoint() string {
	if x != nil {
		return x.EarnCostPerPoint
	}
	return ""
}

func (x *Partner) GetRedeemCostPerPoint() string {
	if x != nil {
		return x.RedeemCostPerPoint
	}
	return ""
}

func (x *Partner) GetStartsFrom() string {
	if x != nil {
		return x.StartsFrom
	}
	return ""
}

func (x *Partner) GetEndsBefore() string {
	if x != nil {
		return x.EndsBefore
	}
	return ""
}

var File_rewardchain_rewardchain_partner_proto protoreflect.FileDescriptor

var file_rewardchain_rewardchain_partner_proto_rawDesc = []byte{
	0x0a, 0x25, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xed, 0x03, 0x0a, 0x07, 0x50, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x12, 0x2f, 0x0a, 0x13, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6c, 0x69,
	0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74,
	0x79, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x6e, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x5f, 0x6c, 0x69, 0x71,
	0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6f, 0x6e,
	0x48, 0x6f, 0x6c, 0x64, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x2d, 0x0a,
	0x13, 0x65, 0x61, 0x72, 0x6e, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x61, 0x72, 0x6e,
	0x43, 0x6f, 0x73, 0x74, 0x50, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x15,
	0x72, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x64,
	0x65, 0x65, 0x6d, 0x43, 0x6f, 0x73, 0x74, 0x50, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x46, 0x72, 0x6f, 0x6d,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x73, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x73, 0x42, 0x65, 0x66, 0x6f, 0x72,
	0x65, 0x3a, 0x26, 0x8a, 0xe7, 0xb0, 0x2a, 0x21, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2f, 0x78, 0x2f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2f, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x42, 0xd1, 0x01, 0x0a, 0x1b, 0x63, 0x6f,
	0x6d, 0x2e, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x0c, 0x50, 0x61, 0x72, 0x74, 0x6e,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0xa2, 0x02, 0x03, 0x52, 0x52, 0x58, 0xaa, 0x02, 0x17, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0xca, 0x02, 0x17, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x5c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0xe2, 0x02, 0x23, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x18, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x3a, 0x3a, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rewardchain_rewardchain_partner_proto_rawDescOnce sync.Once
	file_rewardchain_rewardchain_partner_proto_rawDescData = file_rewardchain_rewardchain_partner_proto_rawDesc
)

func file_rewardchain_rewardchain_partner_proto_rawDescGZIP() []byte {
	file_rewardchain_rewardchain_partner_proto_rawDescOnce.Do(func() {
		file_rewardchain_rewardchain_partner_proto_rawDescData = protoimpl.X.CompressGZIP(file_rewardchain_rewardchain_partner_proto_rawDescData)
	})
	return file_rewardchain_rewardchain_partner_proto_rawDescData
}

var file_rewardchain_rewardchain_partner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rewardchain_rewardchain_partner_proto_goTypes = []interface{}{
	(*Partner)(nil), // 0: rewardchain.rewardchain.Partner
}
var file_rewardchain_rewardchain_partner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rewardchain_rewardchain_partner_proto_init() }
func file_rewardchain_rewardchain_partner_proto_init() {
	if File_rewardchain_rewardchain_partner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rewardchain_rewardchain_partner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rewardchain_rewardchain_partner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rewardchain_rewardchain_partner_proto_goTypes,
		DependencyIndexes: file_rewardchain_rewardchain_partner_proto_depIdxs,
		MessageInfos:      file_rewardchain_rewardchain_partner_proto_msgTypes,
	}.Build()
	File_rewardchain_rewardchain_partner_proto = out.File
	file_rewardchain_rewardchain_partner_proto_rawDesc = nil
	file_rewardchain_rewardchain_partner_proto_goTypes = nil
	file_rewardchain_rewardchain_partner_proto_depIdxs = nil
}
